# Generated by Django 6.0.4 on 2026-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
