# Generated by Django 6.0.4 on 2026-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0002_venue_city_venue_country_venue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
