# Generated by Django 6.0.4 on 2026-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0002_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
