# Generated by Django 6.0.4 on 2026-05-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0003_show_recurrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openmic',
            old_name='weekly_recurrence',
            new_name='recurrence',
        ),
    ]
