# Generated by Django 6.0.4 on 2026-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0004_rename_weekly_recurrence_openmic_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
