# Generated by Django 6.0.4 on 2026-05-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0005_alter_show_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='beer_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='cover_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='requires_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='seating',
            field=models.BooleanField(default=False),
        ),
    ]
