# Generated by Django 6.0.4 on 2026-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0006_venue_beer_only_venue_cover_charge_venue_outdoor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='writersround',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
