# Generated by Django 6.0.4 on 2026-06-13 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0007_openmic_description_show_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotoForOpenMic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='open_mic_photos/')),
                ('open_mic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='gigapi.openmic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_mic_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_photos_for_open_mic',
            },
        ),
        migrations.CreateModel(
            name='UserPhotoForWritersRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='writers_round_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writers_round_photos', to=settings.AUTH_USER_MODEL)),
                ('writers_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='gigapi.writersround')),
            ],
            options={
                'db_table': 'user_photos_for_writers_round',
            },
        ),
    ]
