# Generated by Django 6.0.4 on 2026-06-13 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0008_userphotoforopenmic_userphotoforwritersround'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotoForShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='show_photos/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='gigapi.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_photos_for_show',
            },
        ),
    ]
