# Generated by Django 5.2.3 on 2026-06-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0009_userphotoforshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='ical_feed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
