# Generated by Django 5.2.3 on 2026-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0010_venue_ical_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writersround',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
