# Generated by Django 5.2.3 on 2026-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0011_add_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writersround',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
