# Generated by Django 5.2.3 on 2026-07-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0012_add_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='scrape_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
