# Generated by Django 5.2.3 on 2026-07-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigapi', '0013_add_venue_scrape_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='scrape_url',
        ),
    ]
